### ISSUE TITLE
Remove leading slashes es the plugin_dir_url function returns a path already appends a trailing slash

### ISSUE THREAD

**Issue by dalmadima** [Arkenon/slick-slider-block#4]
Remove leading slashes es the plugin_dir_url function returns a path already appends a trailing slash. see https://developer.wordpress.org/reference/functions/plugin_dir_url/

see Pull-Request: https://github.com/Arkenon/slick-slider-block/pull/2

**Comment by Arkenon** [comment]
Thank you. I have approved your pull request.
